#!/usr/env/bin bash
mkdir -p ~/tools
mkdir -p ~/bin

sudo apt install -y nmap curl sqlmap openvpn nikto python-pip smbclient nmap

sudo pip install pwntools
sudo pip install scapy

# searchsploit
git clone https://github.com/offensive-security/exploitdb.git ~/tools/exploitdb
sed 's|path_array+=(.*)|path_array+=("~/tools/exploitdb")|g' ~/tools/exploitdb/.searchsploit_rc > ~/.searchsploit_rc
ln -sf ~/tools/exploitdb/searchsploit ~/bin/searchsploit

# dirsearch
git clone  https://github.com/maurosoria/dirsearch ~/tools/dirsearch
ln -sf ~/tools/dirsearch/dirsearch.py ~/bin/dirsearch

#enum4linux
git clone https://github.com/portcullislabs/enum4linux.git ~/tools/enum4linux
ln -sf ~/tools/enum4linux/enum4linux.pl ~/bin/enum4linux

